name: config
description: determine the parameters for build and deploy

outputs:
  environments:
    description: an array of environments in JSON
    value: ${{ steps.run.outputs.environments }}

runs:
  using: composite
  steps:
    - uses: actions/github-script@v5
      id: run
      with:
        script: |
          const script = require('./.github/actions/deploy-config/run.js')
          script({ github, context, core })
