name: deploy-config
description: determine the parameters for build and deploy

outputs:
  overlay:
    description: overlay to build from
    value: ${{ steps.run.outputs.overlay }}
  namespace:
    description: namespace to deploy to
    value: ${{ steps.run.outputs.namespace }}

runs:
  using: composite
  steps:
    - uses: actions/github-script@v5
      id: run
      with:
        script: |
          const script = require('./.github/actions/deploy-config/run.js')
          script({ github, context, core })
