name: build-push-prebuilt-manifest
description: build and push a prebuilt manifest

inputs:
  kustomize-overlays:
    required: true
    description: path to overlays
  overlay:
    required: true
    description: overlay to build
    default: pr
  service:
    required: true
    description: name of microservice
  substitute:
    required: false
    description: additional variables to substitute

runs:
  using: composite
  steps:
    - uses: int128/kustomize-action@v1
      id: kustomize
      with:
        kustomization: ${{ inputs.kustomize-overlays }}/${{ inputs.overlay }}/kustomization.yaml
    - uses: quipper/monorepo-deploy-actions/substitute@v1
      with:
        files: ${{ steps.kustomize.outputs.files }}
        variables: ${{ inputs.substitute }}
    - uses: quipper/monorepo-deploy-actions/git-push-service@v1
      with:
        manifests: ${{ steps.kustomize.outputs.files }}
        overlay: ${{ inputs.overlay }}
        namespace: prebuilt
        service: ${{ inputs.service }}
        destination-repository: ${{ github.repository }}
        prebuilt: true
