name: manifest-build-push
description: build and push a manifest

inputs:
  kustomization:
    required: true
    description: path to kustomization.yaml
  overlay:
    required: true
    description: overlay to deploy
  namespace:
    required: true
    description: namespace to deploy
  service:
    required: true
    description: name of microservice
  prebuilt:
    required: false
    description: set true to deploy prebuilt manifests
  substitute:
    required: false
    description: additional variables to substitute

runs:
  using: composite
  steps:
    - uses: int128/kustomize-action@v1
      id: kustomize
      with:
        kustomization: ${{ inputs.kustomization }}
    - uses: quipper/monorepo-deploy-actions/substitute@v1
      with:
        files: ${{ steps.kustomize.outputs.files }}
        variables: |
          NAMESPACE=${{ inputs.namespace }}
    - uses: quipper/monorepo-deploy-actions/git-push-service@v1
      with:
        manifests: ${{ steps.kustomize.outputs.files }}
        overlay: ${{ inputs.overlay }}
        namespace: ${{ inputs.namespace }}
        service: ${{ inputs.service }}
        destination-repository: ${{ github.repository }}
        prebuilt: ${{ inputs.prebuilt == true }}
