name: docker-build-push
description: build and push an image
inputs:
  microservice:
    description: name of microservice
    required: true
  context:
    description: docker/build-push-action
    required: true
outputs:
  image:
    description: image with digest
    value: ghcr.io/${{ github.repository }}/${{ inputs.microservice }}@${{ steps.build.outputs.digest }}
runs:
  using: composite
  steps:
    - uses: docker/metadata-action@v3
      id: metadata
      with:
        images: ghcr.io/${{ github.repository }}/${{ inputs.microservice }}
    - uses: int128/docker-build-cache-config-action@v1
      id: cache
      with:
        image: ghcr.io/${{ github.repository }}/cache
        tag-prefix: ${{ inputs.microservice }}--
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - uses: docker/build-push-action@v2
      id: build
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        cache-from: ${{ steps.cache.outputs.cache-from }}
        cache-to: ${{ steps.cache.outputs.cache-to }}
