name: backend--deploy

on:
  pull_request:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
  push:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-config
        id: config

      - uses: ./.github/actions/docker-build-push
        id: docker
        with:
          microservice: backend
          context: backend

      - uses: ./.github/actions/build-push-manifest
        with:
          kustomize-overlays: backend/kubernetes/overlays
          overlay: ${{ steps.config.outputs.overlay }}
          namespace: ${{ steps.config.outputs.namespace }}
          service: backend
          substitute: |
            DOCKER_IMAGE=${{ steps.docker.outputs.image }}

      - if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/build-push-prebuilt-manifest
        with:
          kustomize-overlays: backend/kubernetes/overlays
          service: backend
          substitute: |
            DOCKER_IMAGE=${{ steps.docker.outputs.image }}
