name: backend--deploy

on:
  pull_request:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
  push:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
    branches:
      - main

env:
  microservice: backend

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image: ghcr.io/${{ github.repository }}/${{ env.microservice }}@${{ steps.build.outputs.image }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/${{ env.microservice }}
      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
          tag-prefix: ${{ env.microservice }}--
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        id: build
        with:
          context: backend
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

  manifest:
    needs:
      - docker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-config
        id: config
      - uses: int128/kustomize-action@v1
        id: kustomize
        with:
          kustomization: backend/kubernetes/overlays/${{ steps.config.outputs.overlay }}/kustomization.yaml
      - uses: quipper/monorepo-deploy-actions/substitute@v1
        with:
          files: ${{ steps.kustomize.outputs.directory }}/**/*.yaml
          variables: |
            NAMESPACE=${{ steps.config.outputs.namespace }}
      - uses: quipper/monorepo-deploy-actions/git-push-service@v1
        with:
          manifests: ${{ steps.kustomize.outputs.directory }}/**/*.yaml
          overlay: ${{ steps.config.outputs.overlay }}
          namespace: ${{ steps.config.outputs.namespace }}
          service: ${{ env.microservice }}
          destination-repository: ${{ github.repository }}
