name: backend--deploy

on:
  pull_request:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
  push:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
    branches:
      - main

env:
  microservice: backend

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-build-push
        id: build
        with:
          microservice: backend
          context: backend

  manifest:
    needs:
      - docker
    uses: quipper/monorepo-deploy-actions-demo/.github/workflows/git-push-manifest.yaml@int128/refactor
    with:
      microservice: backend
      kubernetes-directory: backend/kubernetes
      substitute: |
        DOCKER_IMAGE=${{ needs.docker.outputs.image }}
