name: backend--deploy

on:
  pull_request:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
  push:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
    branches:
      - main

env:
  microservice: backend

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-build-push
        id: build
        with:
          microservice: backend
          context: backend

  config:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.config.outputs.environments }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-config
        id: config

  manifest:
    needs:
      - docker
      - config
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.config.outputs.matrix) }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: int128/kustomize-action@v1
        id: kustomize
        with:
          kustomization: backend/kubernetes/overlays/${{ matrix.config.overlay }}/kustomization.yaml
      - uses: quipper/monorepo-deploy-actions/substitute@v1
        with:
          files: ${{ steps.kustomize.outputs.directory }}/**/*.yaml
          variables: |
            NAMESPACE=${{ matrix.config.namespace }}
            DOCKER_IMAGE=${{ needs.docker.outputs.image }}
      - uses: quipper/monorepo-deploy-actions/git-push-service@v1
        with:
          manifests: ${{ steps.kustomize.outputs.directory }}/**/*.yaml
          overlay: ${{ matrix.config.overlay }}
          namespace: ${{ matrix.config.namespace }}
          service: ${{ env.microservice }}
          destination-repository: ${{ github.repository }}
          transient: ${{ github.event_name == 'pull_request' }}
          prebuilt: ${{ matrix.config.prebuilt == true }}
