name: backend--deploy

on:
  pull_request:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
  push:
    paths:
      - .github/workflows/backend--deploy.yaml
      - backend/**
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-build-push
        id: build
        with:
          microservice: backend
          context: backend

  config:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.config.outputs.environments }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-config
        id: config

  manifest:
    needs:
      - docker
      - config
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.config.outputs.matrix) }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/manifest-build-push
        with:
          kustomization: backend/kubernetes/overlays/${{ matrix.config.overlay }}/kustomization.yaml
          overlay: ${{ matrix.config.overlay }}
          namespace: ${{ matrix.config.namespace }}
          service: backend
          prebuilt: ${{ matrix.config.prebuilt }}
          substitute: |
            DOCKER_IMAGE=${{ needs.docker.outputs.image }}
