name: frontend--deploy

on:
  pull_request:
    paths:
      - .github/workflows/frontend--deploy.yaml
      - frontend/**
  push:
    paths:
      - .github/workflows/frontend--deploy.yaml
      - frontend/**
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-config
        id: config

      - uses: ./.github/actions/docker-build-push
        id: docker
        with:
          microservice: frontend
          context: frontend

      - uses: ./.github/actions/kustomize-build-push
        with:
          kustomize-overlays: frontend/kubernetes/overlays
          overlay: ${{ steps.config.outputs.overlay }}
          namespace: ${{ steps.config.outputs.namespace }}
          service: frontend
          substitute: |
            DOCKER_IMAGE=${{ steps.docker.outputs.image }}

      - if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/kustomize-build-push-prebuilt
        with:
          kustomize-overlays: frontend/kubernetes/overlays
          service: frontend
          substitute: |
            DOCKER_IMAGE=${{ steps.docker.outputs.image }}
